// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW6buk7NcF6R3OvCjiU0CHimxMh2V8WBM',
    appId: '1:1091844872462:web:08767529981dbf9f359f5f',
    messagingSenderId: '1091844872462',
    projectId: 'todoapp-f2834',
    authDomain: 'todoapp-f2834.firebaseapp.com',
    storageBucket: 'todoapp-f2834.appspot.com',
    measurementId: 'G-CTK8YVY2YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqM0fPAi1z30k4KHW2wWsC_NTqt3-FWY',
    appId: '1:1091844872462:android:5ae9151c350c70c5359f5f',
    messagingSenderId: '1091844872462',
    projectId: 'todoapp-f2834',
    storageBucket: 'todoapp-f2834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6JzwNMa4tbexlmNKTInRWujMPR1zfyI',
    appId: '1:1091844872462:ios:8c0424bd3ffb5971359f5f',
    messagingSenderId: '1091844872462',
    projectId: 'todoapp-f2834',
    storageBucket: 'todoapp-f2834.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6JzwNMa4tbexlmNKTInRWujMPR1zfyI',
    appId: '1:1091844872462:ios:8c0424bd3ffb5971359f5f',
    messagingSenderId: '1091844872462',
    projectId: 'todoapp-f2834',
    storageBucket: 'todoapp-f2834.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW6buk7NcF6R3OvCjiU0CHimxMh2V8WBM',
    appId: '1:1091844872462:web:cc9b0e71d8c0e544359f5f',
    messagingSenderId: '1091844872462',
    projectId: 'todoapp-f2834',
    authDomain: 'todoapp-f2834.firebaseapp.com',
    storageBucket: 'todoapp-f2834.appspot.com',
    measurementId: 'G-XJ8KVDN5WN',
  );

}